set(_CATKIN_CURRENT_PACKAGE "cim_turtlebot3_mapping")
set(cim_turtlebot3_mapping_VERSION "0.0.0")
set(cim_turtlebot3_mapping_MAINTAINER "Tom Remeeus <info@computerinfor.nl>")
set(cim_turtlebot3_mapping_PACKAGE_FORMAT "2")
set(cim_turtlebot3_mapping_BUILD_DEPENDS "roscpp" "std_msgs")
set(cim_turtlebot3_mapping_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(cim_turtlebot3_mapping_BUILDTOOL_DEPENDS "catkin")
set(cim_turtlebot3_mapping_BUILDTOOL_EXPORT_DEPENDS )
set(cim_turtlebot3_mapping_EXEC_DEPENDS "roscpp" "std_msgs")
set(cim_turtlebot3_mapping_RUN_DEPENDS "roscpp" "std_msgs")
set(cim_turtlebot3_mapping_TEST_DEPENDS )
set(cim_turtlebot3_mapping_DOC_DEPENDS )
set(cim_turtlebot3_mapping_URL_WEBSITE "")
set(cim_turtlebot3_mapping_URL_BUGTRACKER "")
set(cim_turtlebot3_mapping_URL_REPOSITORY "")
set(cim_turtlebot3_mapping_DEPRECATED "")