set(_CATKIN_CURRENT_PACKAGE "cim_turtlebot3_simulation")
set(cim_turtlebot3_simulation_VERSION "0.0.0")
set(cim_turtlebot3_simulation_MAINTAINER "groamer <groamer@todo.todo>")
set(cim_turtlebot3_simulation_PACKAGE_FORMAT "2")
set(cim_turtlebot3_simulation_BUILD_DEPENDS "roscpp" "std_msgs")
set(cim_turtlebot3_simulation_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(cim_turtlebot3_simulation_BUILDTOOL_DEPENDS "catkin")
set(cim_turtlebot3_simulation_BUILDTOOL_EXPORT_DEPENDS )
set(cim_turtlebot3_simulation_EXEC_DEPENDS "roscpp" "std_msgs")
set(cim_turtlebot3_simulation_RUN_DEPENDS "roscpp" "std_msgs")
set(cim_turtlebot3_simulation_TEST_DEPENDS )
set(cim_turtlebot3_simulation_DOC_DEPENDS )
set(cim_turtlebot3_simulation_URL_WEBSITE "")
set(cim_turtlebot3_simulation_URL_BUGTRACKER "")
set(cim_turtlebot3_simulation_URL_REPOSITORY "")
set(cim_turtlebot3_simulation_DEPRECATED "")