set(_CATKIN_CURRENT_PACKAGE "cim_turtlebot3_physical")
set(cim_turtlebot3_physical_VERSION "0.0.0")
set(cim_turtlebot3_physical_MAINTAINER "groamer <groamer@todo.todo>")
set(cim_turtlebot3_physical_PACKAGE_FORMAT "2")
set(cim_turtlebot3_physical_BUILD_DEPENDS "roscpp" "std_msgs")
set(cim_turtlebot3_physical_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(cim_turtlebot3_physical_BUILDTOOL_DEPENDS "catkin")
set(cim_turtlebot3_physical_BUILDTOOL_EXPORT_DEPENDS )
set(cim_turtlebot3_physical_EXEC_DEPENDS "roscpp" "std_msgs")
set(cim_turtlebot3_physical_RUN_DEPENDS "roscpp" "std_msgs")
set(cim_turtlebot3_physical_TEST_DEPENDS )
set(cim_turtlebot3_physical_DOC_DEPENDS )
set(cim_turtlebot3_physical_URL_WEBSITE "")
set(cim_turtlebot3_physical_URL_BUGTRACKER "")
set(cim_turtlebot3_physical_URL_REPOSITORY "")
set(cim_turtlebot3_physical_DEPRECATED "")